### ISSUE TITLE
[Content issue] /chrome/_index.md

### ISSUE THREAD

**Issue by t-jindai** [cookie-status/cookie-status-dev#29]
It seems that chrome started blocking thrid party cookie and webstorage in incognito mode by default from chrome v83.

https://venturebeat.com/2020/05/19/google-chrome-83/#lre-thumb-AWi_smlJs5G85YzVsVJp:~:text=section).-,Third%2Dparty%20cookies%20blocked

**Comment by sahava** [comment]
Yes. However, that’s not a *default* tracking protection. It’s opt-in. A user has to deliberately open an incognito window to enable it. 

I haven’t treated any other non-default settings in this service, so I don’t see why Chrome should get a mention especially since they have no tracking preventions in default mode whatsoever. 

At some point it might be prudent to expand the browser-specific subpages to include more information about the opt-in privacy protection mechanisms

**Comment by mpirog-hw** [comment]
@sahava, just wanted to share an anecdote around Chrome Incognito that changed my perspective on the idea that Incognito mode is a user opt-in scenario. 

I wouldn't have anticipated this Chrome change to be a particularly disruptive one... until it went live. It turns out some organizations programatically force Incognito mode on workstations in the name of perceived security enhancement. Users may not even be aware they're running Incognito.

In my case, tens of thousands of users were impacted when running our application in an embedded context.

**Comment by sahava** [comment]
Thanks - that’s a powerful anecdote but it’s still an example of opt-in - just on a group policy level rather than individual browser. The difference is that against the tens of thousands of Chrome instances that had it automatically set to Incognito, there are tens of millions of default instances where it’s not in Incognito. Hence: opt-in. 

I’m happy to add a new section for opt-in mechanisms, but for now I’ve decided to focus on just the defaults as they are the most impactful.

**Comment by t-jindai** [comment]
@sahava @openfermentation Thank you for your replys!

I did not know that `blocking thrid party cookie and webstorage in incognito mode` is not **default behavior** 💦 

Some of our users in our service reported that our service did not work correctly and then I investigated it.
Finally I turuned out `cookies and webstorage are being blocked in incognito mode` in my chrome too. I have not changed the `opt-in` setting so I missunderstood that was **default behavior in incognito mode**. 

According to @sahava's mention

[incorrect]
> Blocking thrid party cookie and webstorage by default in **all** chrome incognito mode users.

[correct]
> Blocking thrid party cookie and webstorage by default in **some of** chrome incognito mode users.


Is my understanding right ??

**Comment by sahava** [comment]
No - it *is* default in Incognito. My point was that incognito itself is not the default mode in the browser. A user has to “opt-in” by enabling Incognito mode. It’s similar to Private Windows or Strict ETP in Firefox - it’s something the user has to manually enable before the privacy controls kick in.

**Comment by t-jindai** [comment]
@sahava Thank you for you help !! Finally gotchat so I will close this issue !!

**Comment by sahava** [comment]
Added a note about chrome’s referrer policy here: 7347a13cb3c9e17ad912471933e098458ba9df1f
