### ISSUE TITLE
Firefox url tracking parameters

### ISSUE THREAD

**Issue by User6751** [cookie-status/cookie-status-dev#45]
Firefox will remove some url tracking parameters
https://www.bleepingcomputer.com/news/security/new-firefox-privacy-feature-strips-urls-of-tracking-parameters/

**Comment by User6751** [comment]
Firefox also have a experimental Fingerprinting Protection feature can be enable in about:config `privacy.resistFingerprinting`
https://support.mozilla.org/kb/firefox-protection-against-fingerprinting
https://wiki.mozilla.org/Security/Fingerprinting

**Comment by sahava** [comment]
Hi!

Cookiestatus.com only reports on **default** privacy features, because they are the ones that the majority of browser uses rely on. Opt-in privacy features are not reported, because that should include Strict modes, Private Windows, Browser extensions, and so forth.

So until these features enter the "Standard" Enhanced Tracking Protection level, they won't be included on cookiestatus.com.

Thanks!
